var VM {N, T};
var I  {L, T};
var Trans_Flow{Trans_Lines, T};
var Trans_Theta{Trans_Nodes, T};
var Dist_Shift{LS, T};
var Dist_P_ESS{ESS, T};
var Dist_SOC{ESS,T};
var Dist_Flow {L, T};
var Dist_Pfm{L, T};
var Dist_Pto{L, T};
#var Dist_Qfm{L, T};
#var Dist_Qto{L, T};
var P{L, T};
var Q{L, T};
var P_thermal_dist{G_D, T} >= 0;
var Q_thermal_dist{G_D, T};
var P_renewable_dist{RES_D, T};
var Q_renewable_dist{RES_D, T};
var P_thermal_trans{G_T, T} >= 0;
var Block_Dispatch_t{G_T, B, T};
var Block_Dispatch_d{G_D, B, T};
var P_DSO{T};
var Q_DSO{T};
var Footprint_trans{G_T,T};
var Footprint_dist{G_D,T};
var Carbon_T{G_T,T};
var Carbon_D{G_D,T};
var Carbon_SE{T} ;